version: '3.8'

services:
  velocity:
    image: hank880907/rainbowhunter-proxy:latest
    container_name: velocity-proxy
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - /etc/forwarding.secret:/etc/forwarding.secret:ro
    stdin_open: true
    tty: true
